---
kind: pipeline
type: docker
name: main-dev

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: irinapro/nginx-hello
    tag: drone-latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  branch:
    - drone-ci

