---
kind: pipeline
type: docker
name: build

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: 
      from_secret: repo
    tag:
      from_secret: tag
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
    - drone-ci
---
kind: pipeline
name: deploy

steps:
- name: check ansible syntax
  image: plugins/ansible
  environment:
    image:
      from_secret: repo:tag
  settings:
    playbook: ansible/site.yml
    inventory: ansible/production
    syntax_check: true
- name: apply ansible playbook
  image: plugins/ansible
  environment:
    image:
      from_secret: repo:tag
  settings:
    playbook: ansible/site.yml
    inventory: ansible/production
    user: 
      from_secret: ansible_user
    private_key: 
      from_secret: id_rsa
    verbose: 2

