language: ruby

services:
  - docker


before_install:
  - sudo  apt-get update -qq 
  - sudo apt-get -y install python3 python3-pip python3-setuptools
install:
  - pip3 install ansible

script:
  - docker build -t "$IMAGE" .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$IMAGE"
  - echo -n "$SSH_KEY" | base64 -d >> /tmp/private_key && chmod 600 /tmp/private_key
  - echo "$IMAGE"
  - ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -u $ANSIBLE_USER -i ansible/production ansible/site.yml -vvv --private-key /tmp/private_key
on:
  branch: travis-ci


